project:
  name: my-cfn-project
  regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - eu-north-1

tests:
  default:
    template: ./template.yaml
    s3_regional_buckets: true
    parameters:
      DomainName: "$[taskcat_random-string].sagemakertableauinterworksconnector.com"
      CertificateARN: arn:aws:acm:us-east-1:296531645984:certificate/3bace4c3-fdf3-4477-99dd-b1f5960acd02
      HostedZoneId: Z06778352L9E9SA017LSO
      AuthDomain: quickstart-testing-the-sagemaker-aws-tableau-connector
      QSS3KeyPrefix: "my-cfn-project"
      QSS3BucketName: "$[taskcat_autobucket]"
      QSS3BucketRegion: "$[taskcat_current_region]"
