project:
  name: quickstart-interworks-tableau-sagemaker-autopilot
  regions:
  - us-east-1
  # - us-east-2
  # - us-west-1
  # - us-west-2
  # - eu-north-1
  # - eu-central-1
  # - eu-west-1
  # - eu-west-2
  # - eu-west-3

tests:
  default:
    template: templates/sagemaker-tableau-connector.template
    s3_regional_buckets: true
    parameters:
      DomainName: override
      CertificateARN: override
      HostedZoneId: override
      AuthDomain: quickstart-testing-the-sagemaker-aws-tableau-connector
      QSS3KeyPrefix: "quickstart-interworks-tableau-sagemaker-autopilot"
      QSS3BucketName: "$[taskcat_autobucket]"
      QSS3BucketRegion: "$[taskcat_current_region]"
