// Replace the content in <>
// Briefly describe the software. Use consistent and clear branding. 
// Include the benefits of using the software on AWS, and provide details on usage scenarios.
<<<<<<< HEAD
This Quick Start deployment guide provides step-by-step instructions for deploying this solution.

Quick Starts are automated deployments that use AWS CloudFormation templates to launch, configure, and run the AWS compute, network, storage, and other services required to deploy a specific workload on AWS. The Quick Start deployment includes the following:

 - A REST API that can be connected to from Tableau.
 - A suite of AWS Lambda functions that facilitate connectivity between Amazon SageMaker Hosted endpoints and Tableau. 
 - An Amazon Cognito user pool and client that allows for sign up and sign in for users of the solution. 
=======

This Quick Start deploys a serverless application that can be used with Amazon SageMaker and Tableau Server or Tableau Desktop for BI and data visualization capabilities. The Quick Start deployment includes the following:
>>>>>>> 178ebbc7cd44f119812dbc3e40f709f633ae3dbb

* A REST API that can be connected to from Tableau.
* A suite of AWS Lambda functions that facilitate connectivity between Amazon SageMaker AutoPilot and Tableau.
* An Amazon Cognito user pool and client that allows for sign up and sign in for users of the connector.
